#!/usr/bin/env bash
# Deterministic smoke test; invoke explicitly with: bash tests/smoke_artifact_pipeline.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

uv run --script "$ROOT/scripts/select_shortcut_icon_color.py" \
  --prompt 'Expense tracker' --icon calculator --color gold > "$TMPDIR/icon.json"
python3 - "$TMPDIR/icon.json" <<'PY'
import json
import sys

payload = json.load(open(sys.argv[1], encoding="utf-8"))
assert payload["icon"]["glyph_number"] == 59680, payload
assert payload["color"]["name"] == "Gold", payload
PY

python3 - "$TMPDIR/empty.shortcut" <<'PY'
import plistlib
import sys

with open(sys.argv[1], "wb") as handle:
    plistlib.dump(
        {
            "WFWorkflowIcon": {
                "WFWorkflowIconGlyphNumber": 59680,
                "WFWorkflowIconStartColor": 4274264319,
            },
            "WFWorkflowActions": [
                {
                    "WFWorkflowActionIdentifier": "is.workflow.actions.comment",
                    "WFWorkflowActionParameters": {"WFCommentActionText": "Smoke test"},
                },
                {
                    "WFWorkflowActionIdentifier": "is.workflow.actions.comment",
                    "WFWorkflowActionParameters": {
                        "WFCommentActionText": "Shortcuts generated by Shortcuts Playground."
                    },
                },
            ],
        },
        handle,
    )
PY
uv run --script "$ROOT/scripts/validate_shortcut.py" "$TMPDIR/empty.shortcut"

python3 - "$TMPDIR/invalid.shortcut" <<'PY'
import plistlib
import sys

with open(sys.argv[1], "wb") as handle:
    plistlib.dump(
        {
            "WFWorkflowActions": [
                {
                    "WFWorkflowActionIdentifier": "is.workflow.actions.not-real",
                    "WFWorkflowActionParameters": {},
                }
            ]
        },
        handle,
    )
PY
if uv run --script "$ROOT/scripts/validate_shortcut.py" "$TMPDIR/invalid.shortcut" >/dev/null 2>&1; then
  echo 'validator accepted an unknown action identifier' >&2
  exit 1
fi

if bash "$ROOT/scripts/sign_shortcut.sh" "$TMPDIR/empty.shortcut" >/dev/null 2>&1; then
  echo 'sign_shortcut.sh accepted an implicit output directory' >&2
  exit 1
fi

echo 'Artifact pipeline smoke test passed.'
