from __future__ import annotations

import os
import plistlib
import subprocess
from pathlib import Path

import validate_shortcut

SKILL_DIR = Path(__file__).resolve().parents[1]


def _base_plist(identifier: str) -> dict[str, object]:
    return {
        "WFWorkflowIcon": {
            "WFWorkflowIconGlyphNumber": 59680,
            "WFWorkflowIconStartColor": 4274264319,
        },
        "WFWorkflowActions": [
            {
                "WFWorkflowActionIdentifier": identifier,
                "WFWorkflowActionParameters": {"WFCommentActionText": "Generated by Shortcuts Playground."},
            },
            {
                "WFWorkflowActionIdentifier": "is.workflow.actions.comment",
                "WFWorkflowActionParameters": {"WFCommentActionText": "Shortcuts generated by Shortcuts Playground."},
            },
        ],
    }


def test_validator_accepts_known_action_and_rejects_unknown() -> None:
    allowed = {"is.workflow.actions.comment"}
    accepted, first_error = validate_shortcut.validate(_base_plist("is.workflow.actions.comment"), allowed)
    assert accepted == []
    assert first_error is None
    rejected, first_error = validate_shortcut.validate(_base_plist("is.workflow.actions.not-real"), allowed)
    assert any("Unknown action identifier" in error for error in rejected)
    assert first_error is not None


def test_validator_rejects_invalid_icon_and_required_input() -> None:
    invalid_icon = _base_plist("is.workflow.actions.comment")
    invalid_icon["WFWorkflowIcon"] = {"WFWorkflowIconGlyphNumber": 1, "WFWorkflowIconStartColor": 2}
    errors, _ = validate_shortcut.validate(invalid_icon, {"is.workflow.actions.comment"}, {59680}, {4274264319})
    assert any("GlyphNumber" in error for error in errors)
    bad_url = _base_plist("is.workflow.actions.openurl")
    errors, _ = validate_shortcut.validate(bad_url, {"is.workflow.actions.comment", "is.workflow.actions.openurl"})
    assert any("Missing WFInput" in error for error in errors)


def test_validate_then_sign_wrapper_refuses_implicit_output(tmp_path: Path) -> None:
    source = tmp_path / "shortcut.shortcut"
    with source.open("wb") as handle:
        plistlib.dump(_base_plist("is.workflow.actions.comment"), handle)
    validate = subprocess.run(
        ["uv", "run", "--script", str(SKILL_DIR / "scripts/validate_shortcut.py"), str(source)],
        check=False,
        capture_output=True,
        text=True,
        env=os.environ | {"SHORTCUTS_PLAYGROUND_TARGET_MACOS": "latest"},
    )
    assert validate.returncode == 0, validate.stderr + validate.stdout
    signing = subprocess.run(
        ["bash", str(SKILL_DIR / "scripts/sign_shortcut.sh"), str(source)],
        check=False,
        capture_output=True,
        text=True,
    )
    assert signing.returncode == 64
    assert "Missing --output-dir" in signing.stderr
