from __future__ import annotations

import os
import plistlib
import subprocess
from pathlib import Path

import pytest
import sign_shortcut
import validate_shortcut

SKILL_DIR = Path(__file__).resolve().parents[1]


def _base_plist(identifier: str) -> dict[str, object]:
    return {
        "WFWorkflowIcon": {
            "WFWorkflowIconGlyphNumber": 59680,
            "WFWorkflowIconStartColor": 4274264319,
        },
        "WFWorkflowActions": [
            {
                "WFWorkflowActionIdentifier": identifier,
                "WFWorkflowActionParameters": {
                    "WFCommentActionText": "Generated by Shortcuts Playground.",
                },
            },
            {
                "WFWorkflowActionIdentifier": "is.workflow.actions.comment",
                "WFWorkflowActionParameters": {
                    "WFCommentActionText": "Shortcuts generated by Shortcuts Playground.",
                },
            },
        ],
    }


def test_validator_accepts_known_action_and_rejects_unknown() -> None:
    allowed = {"is.workflow.actions.comment"}
    accepted, first_error = validate_shortcut.validate(
        _base_plist("is.workflow.actions.comment"),
        allowed,
    )
    assert accepted == []
    assert first_error is None
    rejected, first_error = validate_shortcut.validate(
        _base_plist("is.workflow.actions.not-real"),
        allowed,
    )
    assert any("Unknown action identifier" in error for error in rejected)
    assert first_error is not None


def test_validator_rejects_invalid_icon_and_required_input() -> None:
    invalid_icon = _base_plist("is.workflow.actions.comment")
    invalid_icon["WFWorkflowIcon"] = {
        "WFWorkflowIconGlyphNumber": 1,
        "WFWorkflowIconStartColor": 2,
    }
    errors, _ = validate_shortcut.validate(
        invalid_icon,
        {"is.workflow.actions.comment"},
        {59680},
        {4274264319},
    )
    assert any("GlyphNumber" in error for error in errors)
    bad_url = _base_plist("is.workflow.actions.openurl")
    errors, _ = validate_shortcut.validate(
        bad_url,
        {"is.workflow.actions.comment", "is.workflow.actions.openurl"},
    )
    assert any("Missing WFInput" in error for error in errors)


def test_validate_then_sign_wrapper_refuses_implicit_output(tmp_path: Path) -> None:
    source = tmp_path / "shortcut.shortcut"
    with source.open("wb") as handle:
        plistlib.dump(_base_plist("is.workflow.actions.comment"), handle)
    validate = subprocess.run(
        [
            "uv",
            "run",
            "--script",
            str(SKILL_DIR / "scripts/validate_shortcut.py"),
            str(source),
        ],
        check=False,
        capture_output=True,
        text=True,
        env=os.environ | {"SHORTCUTS_PLAYGROUND_TARGET_MACOS": "latest"},
    )
    assert validate.returncode == 0, validate.stderr + validate.stdout
    signing = subprocess.run(
        [
            "uv",
            "run",
            "--script",
            str(SKILL_DIR / "scripts/cli.py"),
            "sign",
            str(source),
        ],
        check=False,
        capture_output=True,
        text=True,
    )
    assert signing.returncode == 2
    assert "Missing --output-dir" in signing.stderr


def test_empty_output_directory_environment_stays_missing(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    source = tmp_path / "shortcut.shortcut"
    source.write_bytes(b"plist")
    monkeypatch.setenv("SHORTCUTS_PLAYGROUND_OUTPUT_DIR", "")
    monkeypatch.delenv("SHORTCUTS_PLAYGROUND_SIGNING_MODE", raising=False)

    assert sign_shortcut.main([str(source)]) == 2
    assert "Missing --output-dir" in capsys.readouterr().err
    assert list(tmp_path.iterdir()) == [source]


@pytest.mark.parametrize("mode", ["", "not-a-signing-mode"])
def test_invalid_signing_mode_environment_is_rejected(
    mode: str,
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    monkeypatch.setenv("SHORTCUTS_PLAYGROUND_SIGNING_MODE", mode)
    with pytest.raises(SystemExit) as error:
        sign_shortcut._parse_args(["input.shortcut", "--output-dir", str(tmp_path)])
    assert error.value.code == 2


def test_explicit_signing_mode_overrides_invalid_environment(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    monkeypatch.setenv("SHORTCUTS_PLAYGROUND_SIGNING_MODE", "invalid")
    args = sign_shortcut._parse_args(
        [
            "input.shortcut",
            "--mode",
            "anyone",
            "--output-dir",
            str(tmp_path),
        ],
    )
    assert args.mode == "anyone"


def test_binary_retry_removes_partial_signing_output(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    source = tmp_path / "input.shortcut"
    output = tmp_path / "output.shortcut"
    source.write_bytes(b"plist")
    output.write_bytes(b"partial")

    def fake_run(command: list[str]) -> subprocess.CompletedProcess[str]:
        if "-convert" in command:
            assert not output.exists()
        return subprocess.CompletedProcess(command, 0, "", "")

    def fake_sign(
        shortcuts: str,
        mode: str,
        sign_source: Path,
        sign_output: Path,
    ) -> int:
        del shortcuts, mode, sign_source
        assert sign_output == output
        assert not sign_output.exists()
        return 0

    monkeypatch.setattr(sign_shortcut, "_run", fake_run)
    monkeypatch.setattr(sign_shortcut, "_sign", fake_sign)

    assert (
        sign_shortcut._retry_binary("plutil", "shortcuts", "anyone", source, output)
        == 0
    )
