#!/bin/sh
set -eu

git diff --cached --check
cargo fmt --manifest-path sync/Cargo.toml --all -- --check
cargo clippy --locked --manifest-path sync/Cargo.toml --workspace --all-targets -- --deny warnings
