#!/bin/sh
set -eu

cargo fmt --manifest-path sync/Cargo.toml --all -- --check
cargo clippy --locked --manifest-path sync/Cargo.toml --workspace --all-targets -- --deny warnings
cargo test --locked --manifest-path sync/Cargo.toml --workspace
