use std::collections::BTreeSet;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::time::Duration;

use sha2::{Digest, Sha256};

use crate::packages::PackageError;
use crate::packages::process::{
    CommandOutcome, install_inferred_import_packages, pick_bun_runner, run_command_outcome,
};

/// File and directory entry names generated by extension package dependency installation.
pub const GENERATED_EXTENSION_ENTRY_NAMES: [&str; 4] =
    ["package.json", "node_modules", "bun.lock", "bun.lockb"];

/// Persisted schema for extension hook state files.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ExtensionHookStateFile {
    pub fingerprint: String,
    #[serde(rename = "generatedEntries")]
    pub generated_entries: Vec<String>,
}

/// Evaluation outcome for extension hook state before running synchronization jobs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PreparedExtensionHookState {
    pub fingerprint: String,
    pub generated_entries: Vec<String>,
    pub preserve_paths: Vec<PathBuf>,
    pub should_skip: bool,
    pub should_refresh_state: bool,
}

/// Discovers all package directories containing `package.json` under an extensions root.
pub fn iter_extension_packages(root: impl AsRef<Path>) -> io::Result<Vec<PathBuf>> {
    let root_path = root.as_ref();
    if !root_path.is_dir() {
        return Ok(Vec::new());
    }

    let mut packages = Vec::new();
    for entry in walkdir::WalkDir::new(root_path).follow_links(false) {
        let Ok(entry) = entry else {
            continue;
        };
        if entry.file_type().is_file() && entry.file_name() == "package.json" {
            let path = entry.path();
            let Ok(rel_path) = path.strip_prefix(root_path) else {
                continue;
            };

            let in_node_modules = rel_path
                .components()
                .any(|c| c.as_os_str() == "node_modules");

            if !in_node_modules && let Some(parent) = path.parent() {
                packages.push(parent.to_path_buf());
            }
        }
    }
    packages.sort();
    Ok(packages)
}

/// Checks whether a package directory needs `bun install` run.
#[must_use]
pub fn needs_node_install(package_dir: &Path) -> bool {
    package_dir.join("package.json").is_file() && !package_dir.join("node_modules").exists()
}

/// Executes an installation command in a package directory, logging any failure.
#[must_use]
pub fn run_install(command: &[&str], package_dir: &Path, timeout: Duration) -> bool {
    let outcome = run_command_outcome(command, Some(package_dir), timeout);
    if outcome == CommandOutcome::Success {
        true
    } else {
        log_install_failure(command, package_dir, &outcome);
        false
    }
}

fn log_install_failure(command: &[&str], package_dir: &Path, outcome: &CommandOutcome) {
    let cmd_name = command.first().copied().unwrap_or("");
    match outcome {
        CommandOutcome::Success => {}
        CommandOutcome::MissingCommand => {
            eprintln!("sync: missing installer: {cmd_name}");
        }
        CommandOutcome::Failure { detail } => {
            eprintln!(
                "sync: deps install failed in {}: {cmd_name} ({detail})",
                package_dir.display()
            );
        }
        CommandOutcome::TimedOut => {
            eprintln!(
                "sync: deps install timed out in {}: {cmd_name}",
                package_dir.display()
            );
        }
    }
}

/// Installs dependencies for all extension packages found in `source_root` into `target` root.
pub fn install_extension_deps(
    root: impl AsRef<Path>,
    source_root: impl AsRef<Path>,
    timeout_ms: u64,
    runner: Option<&Path>,
) -> Result<bool, PackageError> {
    let root_path = root.as_ref();
    let source_root_path = source_root.as_ref();
    let mut results = Vec::new();

    for source_package_dir in iter_extension_packages(source_root_path)? {
        let rel = source_package_dir
            .strip_prefix(source_root_path)
            .unwrap_or(&source_package_dir);
        let package_dir = root_path.join(rel);

        if !needs_node_install(&package_dir) {
            results.push(true);
            continue;
        }

        let runner_buf;
        let bun = if let Some(r) = runner {
            r
        } else if let Some(r) = pick_bun_runner() {
            runner_buf = r;
            &runner_buf
        } else {
            eprintln!("sync: bun is required for {}", package_dir.display());
            results.push(false);
            continue;
        };

        let bun_str = bun.to_str().unwrap_or("bun");
        let timeout = Duration::from_millis(timeout_ms);
        let success = run_install(&[bun_str, "install"], &package_dir, timeout);
        results.push(success);
    }

    let inferred_success =
        install_inferred_import_packages(root_path, timeout_ms, source_root_path, runner)?;
    results.push(inferred_success);

    Ok(results.into_iter().all(|b| b))
}

fn normalize_relative_path(path: &Path) -> String {
    path.components()
        .map(|c| c.as_os_str().to_string_lossy().to_string())
        .collect::<Vec<_>>()
        .join("/")
}

fn should_skip_fingerprint_entry(entry_name: &str) -> bool {
    entry_name == "node_modules" || entry_name == ".git" || entry_name.starts_with('.')
}

fn walk_tree_for_fingerprint(root: &Path, current: &Path, hasher: &mut Sha256) -> io::Result<()> {
    let mut entries = Vec::new();
    for entry in fs::read_dir(current)? {
        let entry = entry?;
        entries.push(entry);
    }

    entries.sort_by_key(std::fs::DirEntry::file_name);

    for entry in entries {
        let file_name = entry.file_name();
        let name = file_name.to_string_lossy();
        if should_skip_fingerprint_entry(&name) {
            continue;
        }

        let absolute = current.join(&file_name);
        let Ok(rel) = absolute.strip_prefix(root) else {
            continue;
        };
        let rel_path = normalize_relative_path(rel);

        let file_type = entry.file_type()?;
        if file_type.is_dir() {
            hasher.update(format!("dir:{rel_path}\n").as_bytes());
            walk_tree_for_fingerprint(root, &absolute, hasher)?;
            continue;
        }

        if file_type.is_symlink() {
            match fs::metadata(&absolute) {
                Ok(meta) if meta.is_dir() => {
                    hasher.update(format!("dir:{rel_path}\n").as_bytes());
                    walk_tree_for_fingerprint(root, &absolute, hasher)?;
                    continue;
                }
                Ok(_) => {}
                Err(_) => {
                    hasher.update(format!("broken:{rel_path}\n").as_bytes());
                    continue;
                }
            }
        }

        if file_type.is_file() || file_type.is_symlink() {
            hasher.update(format!("file:{rel_path}\n").as_bytes());
            if let Ok(content) = fs::read(&absolute) {
                hasher.update(&content);
            }
            hasher.update(b"\n");
        }
    }

    Ok(())
}

/// Computes a deterministic SHA-256 fingerprint of a filesystem tree.
#[must_use]
pub fn fingerprint_tree(root: impl AsRef<Path>) -> String {
    let p = root.as_ref();
    let mut hasher = Sha256::new();
    if !p.exists() {
        hasher.update(b"missing");
        return hex::encode(hasher.finalize());
    }

    let _ = walk_tree_for_fingerprint(p, p, &mut hasher);
    hex::encode(hasher.finalize())
}

fn load_extension_hook_state(path: &Path) -> Option<(ExtensionHookStateFile, bool)> {
    let content = fs::read_to_string(path).ok()?;
    let parsed: serde_json::Value = json5::from_str(&content)
        .or_else(|_| serde_json::from_str(&content))
        .ok()?;

    let fingerprint = parsed.get("fingerprint").and_then(|f| f.as_str())?;
    let raw_entries = parsed.get("generatedEntries").and_then(|e| e.as_array())?;

    let mut normalized_set = BTreeSet::new();
    for entry in raw_entries {
        if let Some(s) = entry.as_str() {
            normalized_set.insert(s.to_owned());
        }
    }

    let mut filtered = Vec::new();
    for entry_name in &normalized_set {
        if GENERATED_EXTENSION_ENTRY_NAMES.contains(&entry_name.as_str()) {
            filtered.push(entry_name.clone());
        }
    }

    let should_refresh_state = filtered.len() != normalized_set.len();
    Some((
        ExtensionHookStateFile {
            fingerprint: fingerprint.to_owned(),
            generated_entries: filtered,
        },
        should_refresh_state,
    ))
}

/// Prepares the extension hook state and determines whether extension sync can be safely skipped.
#[must_use]
pub fn prepare_extension_hook_state(
    source_root: impl AsRef<Path>,
    root: impl AsRef<Path>,
    relative_root: impl AsRef<Path>,
    state_path: impl AsRef<Path>,
) -> PreparedExtensionHookState {
    let source_root_path = source_root.as_ref();
    let root_path = root.as_ref();
    let rel_root_path = relative_root.as_ref();
    let state_file_path = state_path.as_ref();

    let fingerprint = fingerprint_tree(source_root_path);
    let loaded = load_extension_hook_state(state_file_path);

    let Some((previous_state, should_refresh_state)) = loaded else {
        return PreparedExtensionHookState {
            fingerprint,
            generated_entries: Vec::new(),
            preserve_paths: Vec::new(),
            should_skip: false,
            should_refresh_state: false,
        };
    };

    if previous_state.fingerprint != fingerprint {
        return PreparedExtensionHookState {
            fingerprint,
            generated_entries: Vec::new(),
            preserve_paths: Vec::new(),
            should_skip: false,
            should_refresh_state: false,
        };
    }

    let previous_len = previous_state.generated_entries.len();
    let generated_entries: Vec<String> = previous_state
        .generated_entries
        .into_iter()
        .filter(|entry_name| root_path.join(entry_name).exists())
        .collect();

    let should_skip = generated_entries.len() == previous_len;
    let preserve_paths = if should_skip {
        generated_entries
            .iter()
            .map(|entry_name| {
                if rel_root_path.as_os_str().is_empty() {
                    PathBuf::from(entry_name)
                } else {
                    rel_root_path.join(entry_name)
                }
            })
            .collect()
    } else {
        Vec::new()
    };

    PreparedExtensionHookState {
        fingerprint,
        generated_entries,
        preserve_paths,
        should_skip,
        should_refresh_state,
    }
}

/// Records the evaluated extension hook state to disk.
pub fn record_extension_hook_state(
    root: impl AsRef<Path>,
    state_path: impl AsRef<Path>,
    prepared_state: &PreparedExtensionHookState,
) -> io::Result<()> {
    let root_path = root.as_ref();
    let path = state_path.as_ref();

    if let Some(parent) = path.parent()
        && !parent.as_os_str().is_empty()
        && parent != Path::new(".")
    {
        fs::create_dir_all(parent)?;
    }

    let generated_entries: Vec<String> = GENERATED_EXTENSION_ENTRY_NAMES
        .iter()
        .filter(|entry_name| root_path.join(entry_name).exists())
        .map(|s| (*s).to_owned())
        .collect();

    let state = ExtensionHookStateFile {
        fingerprint: prepared_state.fingerprint.clone(),
        generated_entries,
    };

    let formatted = serde_json::to_string_pretty(&state)
        .map_err(|err| io::Error::new(io::ErrorKind::InvalidData, err))?;

    let pid = std::process::id();
    let temp_path = format!("{}.{pid}.tmp", path.to_string_lossy());
    fs::write(&temp_path, format!("{formatted}\n"))?;
    fs::rename(temp_path, path)?;
    Ok(())
}

/// Clears any recorded extension hook state file.
pub fn clear_extension_hook_state(state_path: impl AsRef<Path>) {
    let _ = fs::remove_file(state_path.as_ref());
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_iter_extension_packages() {
        let dir = tempdir().unwrap();
        let ext1 = dir.path().join("ext1");
        let ext2 = dir.path().join("nested/ext2");
        let node_modules = dir.path().join("ext1/node_modules/dep");

        fs::create_dir_all(&ext1).unwrap();
        fs::create_dir_all(&ext2).unwrap();
        fs::create_dir_all(&node_modules).unwrap();

        fs::write(ext1.join("package.json"), "{}").unwrap();
        fs::write(ext2.join("package.json"), "{}").unwrap();
        fs::write(node_modules.join("package.json"), "{}").unwrap();

        let packages = iter_extension_packages(dir.path()).unwrap();
        assert_eq!(packages.len(), 2);
        assert!(packages.contains(&ext1));
        assert!(packages.contains(&ext2));
    }

    #[test]
    fn test_needs_node_install() {
        let dir = tempdir().unwrap();
        assert!(!needs_node_install(dir.path()));

        fs::write(dir.path().join("package.json"), "{}").unwrap();
        assert!(needs_node_install(dir.path()));

        fs::create_dir_all(dir.path().join("node_modules")).unwrap();
        assert!(!needs_node_install(dir.path()));
    }

    #[test]
    fn test_fingerprint_tree_stability() {
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("file.ts"), "const x = 1;").unwrap();
        let fp1 = fingerprint_tree(dir.path());
        let fp2 = fingerprint_tree(dir.path());
        assert_eq!(fp1, fp2);

        fs::write(dir.path().join("file.ts"), "const x = 2;").unwrap();
        let fp3 = fingerprint_tree(dir.path());
        assert_ne!(fp1, fp3);
    }

    #[test]
    fn test_extension_hook_state_lifecycle() {
        let dir = tempdir().unwrap();
        let source_root = dir.path().join("source");
        let root = dir.path().join("root");
        let state_path = dir.path().join("state.json");

        fs::create_dir_all(&source_root).unwrap();
        fs::create_dir_all(&root).unwrap();
        fs::write(source_root.join("index.ts"), "export default {};").unwrap();

        let prepared = prepare_extension_hook_state(&source_root, &root, "", &state_path);
        assert!(!prepared.should_skip);

        record_extension_hook_state(&root, &state_path, &prepared).unwrap();
        assert!(state_path.exists());

        let prepared_again = prepare_extension_hook_state(&source_root, &root, "", &state_path);
        assert!(prepared_again.should_skip);

        clear_extension_hook_state(&state_path);
        assert!(!state_path.exists());
    }
}
