# -----------------------------------------------------------------------------
# GENERAL
# -----------------------------------------------------------------------------

# do not emit thinking blocks (visually)
hide_agent_reasoning = true

web_search = "disabled"

# -----------------------------------------------------------------------------
# MODEL
# -----------------------------------------------------------------------------

model = "gpt-5.2-codex"
review_model = "gpt-5.2-codex"
model_reasoning_effort = "high"
model_verbosity = "low"
model_reasoning_summary = "detailed"
model_personality = "pragmatic"

# -----------------------------------------------------------------------------
# PERMISSIONS
# -----------------------------------------------------------------------------

approval_policy = "never"
sandbox_mode = "danger-full-access"

[sandbox_workspace_write]
exclude_slash_tmp = false
network_access = true

[shell_environment_policy]
# "all", "core", "none"
inherit = "core"

# -----------------------------------------------------------------------------
# FEATURES
# -----------------------------------------------------------------------------

[features]
apply_patch_freeform = true # EXP
child_agents_md = true # EXP
collab = true # EXP
collaboration_modes = true # EXP
personality = true # EXP
remote_compaction = true
shell_snapshot = true
skills = true
sqlite = true # EXP
undo = true # EXP
unified_exec = true

# steer = ENTER ; queue = TAB
steer = true

# -----------------------------------------------------------------------------
# MISC
# -----------------------------------------------------------------------------
[history]
persistence = "save-all"

[analytics]
enabled = false

[feedback]
enabled = false

[notice]
hide_rate_limit_model_nudge = true
